---
name: Hao
surname: Wu
position: Senior Data Scientist
address: Ricardo Energy & Environment
www: moho.netlify.com
email: hao.wu@ricardo.com
github: mohowu
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::moderncv:
    theme: fancy
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
library(dplyr)
library(lubridate)
library(glue)
library(readr)
library(tidyr)
```

# Education

```{r}

read_csv("https://docs.google.com/spreadsheets/d/13nOKX19g6xCLdeEzYrrs__gq8XOb4F3HSCzinfEXrQQ/pub?output=csv") %>% 
  fill(when, what, where) %>% 
  detailed_entries(what = what, 
                   when = when, 
                   where = where, 
                   why = why)
```

# Employment

```{r}

read_csv("https://docs.google.com/spreadsheets/d/1ETdDJGgHBfp2cYTPwX8GS34xaHrYzo5EIeqNCpmyIw8/pub?output=csv") %>% 
  fill(start, end, what, where) %>% 
  mutate(when = glue("{start} - {end}")) %>% 
  detailed_entries(what = what, 
                   when = when, 
                   where = where, 
                   why = why)


```


# Techinal Skills

## Programming Languages

```{r}

tribble(
  ~language, ~level,
  "R", "Proficient",
  "MySQL", "Intermediate",
  "CSS, HTML, Bash, Python", "Basic"
) %>% 
  brief_entries(language, level)

```

## Software

```{r}

tribble(
  ~language, ~level,
  "RStudio, ADMS-Urban, MS Word", "Advanced",
  "ArcGIS, FME, MS Excel, Sketchup, Fusion 360", "Intermediate"
) %>% 
  brief_entries(language, level)

```

# Teaching Experience

```{r}

read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTw1G9EQTq60UwuYYDVba9yMhX4xSxghHtbD0NB0XlIHkNsU7dA-hLiY1As1r8WXFAfopCPA_Kg-GK8/pub?output=csv") %>% 
  brief_entries(what = what,
                when = when,
                with = where)


```

# Honours and Awards

```{r}

read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSgiz8F9r8e2ZhibCoPUWQnEXFxWittlZZ-Os2ZsIElBWC07qZSS0hWYdTATPqLvneK8JpzWnyW8YDF/pub?gid=0&single=true&output=csv") %>% 
  brief_entries(what = what,
                when = when)

```

# Conferences and Training Courses

```{r}

read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vR4RdajvSkIBAwv3lVP6Rx7UJhNpNABkdP85piY6-bC8wI-r4j_gichS6_qTE_hVEZs3G95NqF8Qnif/pub?gid=0&single=true&output=csv") %>% 
  brief_entries(what = what,
                when = when,
                with = where)

```



# Publications

```{r}
# 
# bibliography_entries("packages.bib") %>%
#   arrange(desc(author$family), issued)
```

